cluster_name: tee-hcp
tls:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIICBDCCAamgAwIBAgIRANRP5SRu3hwI9t1ROSTbG7cwCgYIKoZIzj0EAwIwLjEV
    MBMGA1UEChMMVHJhZWZpayBMYWJzMRUwEwYDVQQDEwxUcmFlZmlrRUUgQ0EwIBcN
    MjExMDA0MTk1NDAxWhgPMjEyMTA5MTAxOTU0MDFaMBkxFzAVBgNVBAMTDmNsaWVu
    dC50ZWUtaGNwMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3OsPIigw9r1oxTQj
    UgQVx85Gln8MDYbJvNKoJl8Cj7FW7tfgmUtMMLfPguKQQxG1ZtAGm5IMo+yjXD5d
    GsCRDqOBujCBtzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwIw
    DAYDVR0TAQH/BAIwADApBgNVHQ4EIgQgYG4GP7YC4B+0TM6RA2i5qY20FWH0oans
    AizrHAzGhhIwKwYDVR0jBCQwIoAg9+t9NDKRmYuxGrvvLaHfOA4MBTXRiHHEcSZc
    yQkPkGUwKgYDVR0RBCMwIYIOY2xpZW50LnRlZS1oY3CCCWxvY2FsaG9zdIcEfwAA
    ATAKBggqhkjOPQQDAgNJADBGAiEA24Arvz4uoEd7Ry06WYVdhGwIgt0PK8nko0Dv
    mGiQwrUCIQCaubuR5E9nTBNLlIjKNDtQPIXcmPuCHBkvSm3YKFjeSQ==
    -----END CERTIFICATE-----
  key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEILg/+Z59qNqD/04t/Y/XBm4cF1BwfPeHsMW8jlo0txj5oAoGCCqGSM49
    AwEHoUQDQgAE3OsPIigw9r1oxTQjUgQVx85Gln8MDYbJvNKoJl8Cj7FW7tfgmUtM
    MLfPguKQQxG1ZtAGm5IMo+yjXD5dGsCRDg==
    -----END EC PRIVATE KEY-----
  ca: |
    -----BEGIN CERTIFICATE-----
    MIIB1zCCAX2gAwIBAgIQWqJTL/hUnGRDKKT8q7LObjAKBggqhkjOPQQDAjAuMRUw
    EwYDVQQKEwxUcmFlZmlrIExhYnMxFTATBgNVBAMTDFRyYWVmaWtFRSBDQTAgFw0y
    MTEwMDQxOTUxNTJaGA8yMTIxMDkxMDE5NTE1MlowLjEVMBMGA1UEChMMVHJhZWZp
    ayBMYWJzMRUwEwYDVQQDEwxUcmFlZmlrRUUgQ0EwWTATBgcqhkjOPQIBBggqhkjO
    PQMBBwNCAASM+Iu8ykUDDYBfA+5nHOYecRDbM0/ZxU/HknKsnt0ojp5umcuF87c6
    iDW38CcJJtqXfPYD2APyPy4sy8AgsNjVo3sweTAOBgNVHQ8BAf8EBAMCAYYwDwYD
    VR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg9+t9NDKRmYuxGrvvLaHfOA4MBTXRiHHE
    cSZcyQkPkGUwKwYDVR0jBCQwIoAg9+t9NDKRmYuxGrvvLaHfOA4MBTXRiHHEcSZc
    yQkPkGUwCgYIKoZIzj0EAwIDSAAwRQIgU5d0g51M6oAsYCTuqaZCcAwHC44h9FyA
    o9heuAbKYvECIQDoRZQrlCNAxtvL/T72Nqnd7nI+tpb/Eq5UXq3eaQRhKQ==
    -----END CERTIFICATE-----
kubernetes:
  config_path: /home/douglas/.kube/config
  namespace: traefikee
  forwarded_port: 0
pluginregistrytoken: ""
